version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: task-manager-db
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass123
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d taskmanager"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
  redis-data: