[build]
  base = "client"
  command = "npm install --no-workspaces && npm run build"
  publish = "dist"
  ignore = "/api/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_WORKSPACES = "false"