# Render.com deployment configuration
services:
  # Backend API
  - type: web
    name: task-manager-api
    runtime: node
    repo: https://github.com/LailaRizvi1997/task-manager
    rootDirectory: server
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://YOUR-FRONTEND-URL.vercel.app # Update after deployment

  # Frontend (Alternative to Vercel)
  - type: static
    name: task-manager-frontend
    repo: https://github.com/YOUR_USERNAME/task-manager # Update with your repo
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

# Database
databases:
  - name: task-manager-db
    databaseName: taskmanager
    user: taskuser
    plan: free # PostgreSQL database